/* Cantori content data — generated by editor.html. Edit via the editor,
   or by hand (it's plain data). The game loads window.CANTORI_DATA. */
window.CANTORI_DATA = {
  "monsters": {
    "rat": {
      "name": "Rat",
      "hp": 8,
      "minFloor": 1,
      "glyph": "r",
      "color": "#c9b48f",
      "speed": 1,
      "eva": 12,
      "atkMin": 1,
      "atkMax": 4,
      "acc": 5
    },
    "bat": {
      "name": "Bat",
      "flying": true,
      "minFloor": 1,
      "glyph": "b",
      "color": "#b491d6",
      "hp": 5,
      "speed": 1,
      "atkMin": 1,
      "atkMax": 4,
      "eva": 20,
      "acc": 5
    },
    "snake": {
      "name": "Snake",
      "hp": 8,
      "glyph": "s",
      "color": "#7ec98a",
      "minFloor": 3,
      "speed": 1,
      "acc": 10,
      "atkMin": 1,
      "eva": 30,
      "atkMax": 6
    },
    "spider": {
      "walkSpeed": 0.8,
      "name": "Spider",
      "atkMax": 5,
      "minFloor": 6,
      "glyph": "x",
      "color": "#d68f8f",
      "speed": 1,
      "acc": 15,
      "eva": 10,
      "range": 4,
      "ranged": true,
      "atkMin": 1,
      "hp": 12
    },
    "wolf": {
      "name": "Wolf",
      "acc": 0,
      "glyph": "W",
      "color": "#9aa0a8",
      "hp": 16,
      "atkMax": 6,
      "speed": 1,
      "minFloor": 2,
      "atkMin": 2,
      "eva": 15
    },
    "bee": {
      "name": "Bee",
      "flying": true,
      "hp": 10,
      "atkMin": 2,
      "atkMax": 6,
      "acc": 9,
      "glyph": "e",
      "color": "#e6c34a",
      "ranged": true,
      "range": 2,
      "speed": 1,
      "eva": 25,
      "minFloor": 2
    },
    "bear": {
      "attackSpeed": 1,
      "name": "Bear",
      "hp": 35,
      "atkMin": 2,
      "atkMax": 4,
      "acc": 15,
      "eva": 6,
      "charge": true,
      "glyph": "B",
      "color": "#8a6a44",
      "speed": 1,
      "minFloor": 4,
      "walkSpeed": 1
    },
    "harpy": {
      "name": "Harpy",
      "flying": true,
      "atkMax": 12,
      "acc": 12,
      "eva": 14,
      "ranged": true,
      "range": 4,
      "glyph": "H",
      "color": "#6b6f7a",
      "minFloor": 6,
      "hp": 35,
      "speed": 1,
      "atkMin": 2
    },
    "jackal": {
      "walkSpeed": 1.2,
      "speed": 1,
      "name": "Jackal",
      "hp": 3,
      "atkMin": 1,
      "atkMax": 2,
      "glyph": "j",
      "color": "#b79a6b"
    },
    "hornet": {
      "walkSpeed": 1.2,
      "attackSpeed": 1.2,
      "speed": 1,
      "name": "Hornet",
      "flying": true,
      "hp": 2,
      "atkMin": 2,
      "atkMax": 3,
      "glyph": "h",
      "color": "#e0a13c"
    },
    "ghoul": {
      "walkSpeed": 0.8,
      "attackSpeed": 0.8,
      "speed": 1,
      "name": "Ghoul",
      "hp": 35,
      "atkMin": 3,
      "atkMax": 9,
      "glyph": "G",
      "color": "#9fb07a",
      "minFloor": 11,
      "charge": true
    },
    "wraith": {
      "walkSpeed": 1.2,
      "speed": 1,
      "name": "Wraith",
      "hp": 6,
      "atkMin": 3,
      "atkMax": 4,
      "glyph": "W",
      "color": "#8fa0c0",
      "minFloor": 12
    },
    "phantom": {
      "walkSpeed": 1.2,
      "speed": 1,
      "name": "Phantom",
      "hp": 5,
      "atkMin": 2,
      "atkMax": 4,
      "glyph": "P",
      "color": "#7ee0d0",
      "minFloor": 13
    },
    "imp": {
      "walkSpeed": 1.2,
      "speed": 1,
      "name": "Imp",
      "hp": 5,
      "atkMin": 3,
      "atkMax": 5,
      "glyph": "i",
      "color": "#c0c0e0",
      "minFloor": 14
    },
    "keener": {
      "walkSpeed": 1.2,
      "speed": 1,
      "name": "Keener",
      "hp": 4,
      "atkMin": 2,
      "atkMax": 4,
      "minFloor": 16,
      "glyph": "u",
      "color": "#6fb0d0"
    },
    "emberfiend": {
      "name": "Ember Fiend",
      "hp": 10,
      "atkMin": 4,
      "atkMax": 7,
      "glyph": "d",
      "color": "#e07030",
      "minFloor": 17
    },
    "healing_node": {
      "name": "Healing Node",
      "hp": 25,
      "atkMin": 0,
      "atkMax": 0,
      "glyph": "◈",
      "color": "#8ed69a"
    },
    "Goblin": {
      "name": "Goblin",
      "hp": 20,
      "atkMin": 1,
      "atkMax": 10,
      "glyph": "?",
      "color": "#c0c0c0",
      "speed": 1,
      "walkSpeed": 1,
      "attackSpeed": 1,
      "acc": 8,
      "eva": 10,
      "minFloor": 7
    },
    "Goblin_archer": {
      "name": "Goblin Archer",
      "hp": 15,
      "atkMin": 0,
      "atkMax": 8,
      "glyph": "?",
      "color": "#c0c0c0",
      "acc": 20,
      "eva": 0,
      "range": 4,
      "ranged": true,
      "minFloor": 8
    }
  },
  "gear": {
    "dagger": {
      "cat": "weapon",
      "sub": "dagger",
      "name": "Dagger",
      "dmgMin": 1,
      "speed": 1.25,
      "tier": 1,
      "req": {
        "STR": 0
      },
      "glyph": "/",
      "color": "#cfc3a0",
      "accuracy": 9,
      "dmgMax": 4,
      "rarity": 25
    },
    "sword": {
      "cat": "weapon",
      "sub": "sword",
      "name": "Sword",
      "dmgMin": 2,
      "dmgMax": 6,
      "speed": 1,
      "glyph": "/",
      "color": "#d8e0ec",
      "tier": 1,
      "req": {
        "STR": 10
      },
      "rarity": 25,
      "accuracy": 6
    },
    "big axe": {
      "cat": "weapon",
      "sub": "axe",
      "name": "Big axe",
      "dmgMin": 6,
      "dmgMax": 15,
      "speed": 0.9,
      "glyph": "/",
      "color": "#c8a878",
      "tier": 2,
      "req": {
        "STR": 15
      },
      "accuracy": -15,
      "rarity": 4
    },
    "leather": {
      "cat": "armor",
      "sub": "light",
      "name": "Leather Armor",
      "tier": 1,
      "req": {
        "STR": 0
      },
      "glyph": "[",
      "color": "#b98a5a",
      "defMin": 1,
      "defMax": 4,
      "evasion": 1
    },
    "chain": {
      "cat": "armor",
      "sub": "medium",
      "name": "Chain Mail",
      "tier": 3,
      "glyph": "[",
      "color": "#b9c0c8",
      "req": {
        "STR": 15
      },
      "defMin": 2,
      "defMax": 10,
      "evasion": 0
    },
    "plate": {
      "cat": "armor",
      "sub": "heavy",
      "name": "Plate Armor",
      "tier": 5,
      "glyph": "[",
      "color": "#dfe6f0",
      "req": {
        "STR": 40
      },
      "defMin": 3,
      "defMax": 25,
      "evasion": -10
    },
    "ring_copper": {
      "cat": "ring",
      "name": "Copper Ring",
      "tier": 1,
      "glyph": "o",
      "color": "#c58a4a"
    },
    "ring_silver": {
      "cat": "ring",
      "name": "Silver Ring",
      "tier": 3,
      "glyph": "o",
      "color": "#cfd4dc"
    },
    "charm_bone": {
      "cat": "trinket",
      "name": "Bone Charm",
      "tier": 1,
      "glyph": "*",
      "color": "#d8cfb0"
    },
    "metrognome": {
      "cat": "trinket",
      "name": "Metrognome",
      "glyph": "*",
      "color": "#9ad0ff",
      "variants": [
        "walk",
        "attack"
      ]
    },
    "amulet_jade": {
      "cat": "necklace",
      "name": "Jade Amulet",
      "glyph": "\"",
      "color": "#7ec9a0",
      "tier": 3
    },
    "Axe": {
      "cat": "weapon",
      "sub": "axe",
      "name": "Axe",
      "dmgMax": 12,
      "tier": 1,
      "req": {
        "STR": 10
      },
      "glyph": "/",
      "color": "#cccccc",
      "dmgMin": 4,
      "speed": 0.9,
      "accuracy": -15,
      "rarity": 25
    },
    "spear": {
      "cat": "weapon",
      "sub": "spear",
      "name": "Spear",
      "dmgMin": 2,
      "dmgMax": 6,
      "speed": 0.9,
      "tier": 1,
      "req": {
        "STR": 8
      },
      "range": 2,
      "glyph": "/",
      "color": "#c8b890",
      "accuracy": 3,
      "rarity": 10
    },
    "bow": {
      "cat": "weapon",
      "sub": "bow",
      "name": "Short Bow",
      "speed": 1,
      "tier": 1,
      "req": {
        "STR": 5
      },
      "range": 5,
      "glyph": "}",
      "color": "#b08a4a",
      "dmgMin": 0,
      "dmgMax": 8,
      "accuracy": -10,
      "rarity": 15
    },
    "Shitty_sword": {
      "cat": "weapon",
      "name": "Shitty sword",
      "dmgMin": 1,
      "dmgMax": 2,
      "accuracy": 5,
      "tier": 0,
      "req": {
        "STR": 0
      },
      "glyph": "/",
      "color": "#cccccc",
      "sub": "sword",
      "speed": 1.2,
      "rarity": 0
    },
    "Shitty_armor": {
      "cat": "armor",
      "name": "Shitty armor",
      "req": {
        "STR": 0
      },
      "glyph": "/",
      "color": "#cccccc",
      "sub": "light",
      "defMin": 0,
      "defMax": 1,
      "evasion": 0,
      "tier": 0,
      "rarity": 0
    },
    "cloth": {
      "cat": "armor",
      "name": "Cloth",
      "accuracy": 0,
      "tier": 1,
      "req": {
        "STR": 0
      },
      "glyph": "/",
      "color": "#cccccc",
      "defMin": 0,
      "defMax": 2,
      "evasion": 10,
      "sub": "light"
    }
  },
  "loot": {
    "rarities": [
      {
        "key": "white",
        "name": "",
        "chance": 0.5,
        "color": "#e6e0d2"
      },
      {
        "key": "green",
        "name": "",
        "chance": 0.33,
        "color": "#7ec98a"
      },
      {
        "key": "blue",
        "name": "",
        "chance": 0.12,
        "color": "#5a9fe0"
      },
      {
        "key": "purple",
        "name": "",
        "chance": 0.05,
        "color": "#b491d6"
      },
      {
        "key": "gold",
        "name": "",
        "chance": 0,
        "color": "#f0c14b"
      }
    ],
    "statPool": [
      "STR",
      "INT",
      "VIT",
      "DEX",
      "RES",
      "LCK"
    ],
    "purpleSecondStatChance": 0.75,
    "dropWeights": {
      "gold": 18,
      "gear": 62,
      "consumable": 20
    },
    "categoryWeights": {
      "weapon": 45,
      "armor": 33,
      "ring": 12,
      "necklace": 10
    },
    "trinketRarity": {
      "blue": 40,
      "purple": 40,
      "gold": 20
    },
    "tierBands": [
      {
        "upToFloor": 5,
        "weights": [
          100,
          0,
          0
        ]
      },
      {
        "upToFloor": 10,
        "weights": [
          70,
          30,
          0
        ]
      },
      {
        "upToFloor": 15,
        "weights": [
          30,
          55,
          15
        ]
      },
      {
        "upToFloor": 20,
        "weights": [
          10,
          45,
          45
        ]
      },
      {
        "upToFloor": 25,
        "weights": [
          0,
          25,
          75
        ]
      }
    ],
    "enchants": {
      "fire": {
        "name": "Flaming",
        "icon": "🔥",
        "color": "#ff8f4a",
        "proc": 0.35,
        "slots": [
          "weapon",
          "ring",
          "trinket",
          "necklace"
        ],
        "desc": "Sears on a hit for half the source's power, then keeps burning for a few turns. Only one flame burns at a time.",
        "effect": {
          "type": "burn",
          "burstMult": 0.5,
          "dotTurns": 3
        },
        "tier": 2,
        "tierValues": [
          0.5,
          0.75,
          1,
          1.5,
          3
        ]
      },
      "electric": {
        "name": "Charged",
        "icon": "⚡",
        "color": "#9ad0ff",
        "proc": 0.3,
        "slots": [
          "weapon",
          "ring",
          "necklace"
        ],
        "desc": "A jolt equal to the source's power, with a chance to stun that fades against higher-level foes.",
        "effect": {
          "type": "shock",
          "stunPer": 0.1,
          "burstMult": 0.5
        },
        "tierValues": [
          1,
          1.5,
          2,
          3,
          5
        ]
      },
      "Speed": {
        "name": "Speed",
        "icon": "✦",
        "color": "#bfe0ff",
        "proc": 1,
        "slots": [
          "ring",
          "armor"
        ],
        "desc": "While worn, your attacks cost less time — you act faster. Scales with the item's tier.",
        "effect": {
          "type": "haste",
          "mult": 0.25
        },
        "tierValues": [
          1.1,
          1.2,
          1.3,
          1.5,
          1.75
        ]
      },
      "Swiftness": {
        "name": "Swiftness",
        "icon": "👟",
        "color": "#bfe0ff",
        "proc": 1,
        "slots": [
          "armor",
          "trinket",
          "necklace"
        ],
        "desc": "While worn, your steps cost less time — you cover ground faster than your foes. Scales with the item's tier.",
        "effect": {
          "type": "walkHaste",
          "mult": 0.25
        },
        "tierValues": [
          1.25,
          1.5,
          1.75,
          2,
          2.5
        ]
      },
      "Thorns": {
        "name": "Thorns",
        "icon": "🜲",
        "color": "#cdd6a0",
        "proc": 0.5,
        "slots": [
          "armor",
          "necklace"
        ],
        "desc": "When you're struck, lash back at the attacker for half the damage you took.",
        "effect": {
          "type": "thorns",
          "mult": 0.5
        },
        "tierValues": [
          0.5,
          0.75,
          1,
          1.5,
          2.5
        ]
      },
      "Poison": {
        "name": "Poison",
        "icon": "☠",
        "color": "#9ad06a",
        "proc": 0.2,
        "slots": [
          "weapon",
          "ring"
        ],
        "desc": "Injects a dose equal to a tiered % of the weapon's damage. Doses stack: each proc adds to the poison already ticking, and every turn it deals its current total then fades by 1 — so a big stack keeps hurting long after you've backed off.",
        "effect": {
          "type": "poison"
        },
        "tierValues": [
          0.2,
          0.5,
          0.8,
          1,
          1.5
        ]
      },
      "Defense": {
        "name": "Defense",
        "icon": "✦",
        "color": "#9ad0ff",
        "proc": 1,
        "slots": [
          "armor",
          "ring",
          "necklace"
        ],
        "desc": "Increases the amount of damage reduced from incoming attacks (both the min and max block). Scales with the item's tier.",
        "effect": {
          "type": "defense"
        },
        "tierValues": [
          1,
          2,
          3,
          5,
          8
        ]
      }
    }
  },
  "consumables": {
    "heal": {
      "cat": "potion",
      "name": "Potion of Healing",
      "effect": "heal",
      "weight": 5,
      "glyph": "!",
      "color": "#e0685a"
    },
    "strength": {
      "cat": "potion",
      "name": "Potion of Strength",
      "effect": "strength",
      "weight": 2,
      "glyph": "!",
      "color": "#f0a838"
    },
    "poison": {
      "cat": "potion",
      "name": "Potion of Poison",
      "effect": "poison",
      "weight": 2,
      "glyph": "!",
      "color": "#7ec98a"
    },
    "mapping": {
      "cat": "scroll",
      "name": "Scroll of Magic Mapping",
      "effect": "map",
      "weight": 3,
      "glyph": "?",
      "color": "#cfe6b0"
    },
    "teleport": {
      "cat": "scroll",
      "name": "Scroll of Teleport",
      "effect": "teleport",
      "weight": 2,
      "glyph": "?",
      "color": "#b491d6"
    },
    "torch": {
      "cat": "tool",
      "name": "Torch",
      "effect": "burn",
      "noDrop": true,
      "glyph": "|",
      "color": "#f6b845"
    },
    "vitality": {
      "cat": "potion",
      "name": "Potion of Vitality",
      "effect": "Vitality",
      "glyph": "!",
      "color": "#cccccc"
    },
    "stone_skin": {
      "cat": "potion",
      "name": "Potion of Stone Skin",
      "effect": "Stone Skin",
      "glyph": "!",
      "color": "#cccccc"
    },
    "Intelligence": {
      "cat": "potion",
      "name": "Potion of Intelligence",
      "effect": "intelligence",
      "glyph": "!",
      "color": "#cccccc"
    },
    "skill_point": {
      "cat": "potion",
      "name": "Potion of Insight",
      "effect": "skill_point",
      "noDrop": true,
      "glyph": "!",
      "color": "#f0c14b"
    },
    "scroll_upgrade": {
      "cat": "scroll",
      "name": "Scroll of Upgrade",
      "effect": "upgrade_item",
      "noDrop": true,
      "glyph": "?",
      "color": "#f0c14b"
    },
    "scroll_invisibility": {
      "cat": "scroll",
      "name": "Scroll of Invisibility ",
      "effect": "invisibility",
      "glyph": "!",
      "color": "#cccccc"
    },
    "scroll_thunderclap": {
      "cat": "scroll",
      "name": "Scroll of Thunderclap",
      "effect": "Thunderclap",
      "glyph": "!",
      "color": "#cccccc"
    }
  },
  "traps": {
    "teleport": {
      "name": "Teleport Trap",
      "effect": "teleport_far",
      "weight": 1,
      "glyph": "^",
      "color": "#b491d6"
    },
    "arrow": {
      "name": "Arrow Trap",
      "effect": "arrow",
      "weight": 1,
      "glyph": "↑",
      "color": "#c9a24a"
    },
    "bomb": {
      "name": "Bomb Trap",
      "effect": "bomb",
      "weight": 1,
      "glyph": "◉",
      "color": "#e0685a"
    }
  },
  "boons": {
    "artificer": {
      "name": "Artificer's Tools",
      "desc": "The Guild presses 3-5 Scrolls of Upgrade into your hands at once — each permanently upgrades an equipped item's +X by one, and can't be dropped.",
      "icon": "⚒",
      "color": "#f0c14b"
    },
    "scribe": {
      "name": "Scribe's Intellect",
      "desc": "Your INT rises with your gear: Total Equipment Upgrades × Quality Multiplier (White ×1.0 … Gold ×5.0), rounded to the nearest 0.5.",
      "icon": "📜",
      "color": "#f0c14b"
    },
    "blacksmith": {
      "name": "Blacksmith's Arm",
      "desc": "Your STR rises with your gear: Total Equipment Upgrades × Quality Multiplier (White ×1.0 … Gold ×5.0), rounded to the nearest 0.5.",
      "icon": "🔨",
      "color": "#f0c14b"
    },
    "blessing": {
      "name": "Guild's Blessing",
      "desc": "White drop chance falls by 1% per character level, redistributed equally to Green/Blue/Purple.",
      "icon": "✦",
      "color": "#f0c14b"
    },
    "refinement": {
      "name": "Guild's Refinement",
      "desc": "Doubles the maximum +X a dropped item can roll, and weights the roll toward the higher end.",
      "icon": "💎",
      "color": "#f0c14b"
    },
    "compost": {
      "name": "Compost Pile",
      "desc": "Every 5th kill, gain +1 to a random stat (STR/INT/VIT/DEX).",
      "icon": "🌱",
      "color": "#e0685a"
    },
    "second_chance": {
      "name": "Second Chance",
      "desc": "The first fatal blow you take this run is intercepted — a full heal, then this blessing is spent.",
      "icon": "♻",
      "color": "#e0685a"
    },
    "leper": {
      "name": "Leper Colony",
      "desc": "Immune to poison. On a connecting hit, a chance to poison your target — chance scales with your level and your Maelon blessings (capped at 75%).",
      "icon": "☣",
      "color": "#e0685a"
    },
    "merciful": {
      "name": "Merciful End",
      "desc": "On a connecting hit, if the target's health is below your level%, the blow is instantly fatal.",
      "icon": "🗡",
      "color": "#e0685a"
    },
    "dread": {
      "name": "Endless Dread",
      "desc": "When a foe wounds you, it risks fleeing in terror — chance equal to the average of your VIT/RES/LCK%.",
      "icon": "💀",
      "color": "#e0685a"
    },
    "wall": {
      "name": "Wall of Faith",
      "desc": "Active — tap a tile to raise a 5-tile wall of stone along the nearest axis, shoving any foe caught in it back a step. Cooldown 150 turns.",
      "icon": "🧱",
      "color": "#b491d6"
    },
    "pull": {
      "name": "Faith's Pull",
      "desc": "Active — tap a tile to bend a wide 9×9 swath of ground to Kethara's will for 5 turns, pulling every foe within it toward the center. Cooldown 150 turns.",
      "icon": "🌀",
      "color": "#b491d6"
    },
    "gift": {
      "name": "Gift of the Faithful",
      "desc": "Every 10th kill, gain +1 RES.",
      "icon": "🕊",
      "color": "#b491d6"
    },
    "eye": {
      "name": "Eye of Kethara",
      "desc": "Active — tap a foe to fix it in place for 25 turns. Cooldown falls with RES.",
      "icon": "👁",
      "color": "#b491d6"
    },
    "anger": {
      "name": "Anger of Kethara",
      "desc": "Active — tap a foe to send it into a berserk rage, turning it on whatever's nearest. Cooldown falls with RES.",
      "icon": "😡",
      "color": "#b491d6"
    },
    "foresight": {
      "name": "Future Sight",
      "desc": "Every 10th kill, gain +1 Accuracy and +1 Evasion.",
      "icon": "🔮",
      "color": "#9ad0ff"
    },
    "timed_blow": {
      "name": "Perfectly Timed Blow",
      "desc": "Critical chance rises by 1% for every character level.",
      "icon": "⏱",
      "color": "#9ad0ff"
    },
    "dilating": {
      "name": "Dilating Pupils",
      "desc": "Every 5th kill, gain +1% Haste, permanently.",
      "icon": "👀",
      "color": "#9ad0ff"
    },
    "pride": {
      "name": "The Pride Before The Fall",
      "desc": "At once, +10 to all base stats. But every 15th kill after, -1 to all base stats — with no floor.",
      "icon": "☄",
      "color": "#9ad0ff"
    },
    "speed_of_light": {
      "name": "Speed of Light",
      "desc": "Active — 25 MP for an instant +100% Haste that decays 1%/turn back to baseline. Cooldown 500 turns.",
      "icon": "⚡",
      "color": "#9ad0ff"
    }
  },
  "bosses": {
    "piper": {
      "name": "The Pied Piper",
      "atkMin": 6,
      "atkMax": 10,
      "hp": 200
    },
    "golem": {
      "name": "Stone Golem",
      "atkMin": 1,
      "hp": 400,
      "atkMax": 25
    },
    "cultist": {
      "name": "Cultist",
      "hp": 200,
      "atkMin": 0,
      "atkMax": 20
    },
    "mummy": {
      "name": "The Mummy",
      "hp": 90,
      "atkMin": 7,
      "atkMax": 10
    },
    "demigod": {
      "name": "The Demi-God",
      "hp": 150,
      "atkMin": 9,
      "atkMax": 13
    }
  },
  "biomes": [
    {
      "key": "forest",
      "name": "Forest",
      "floor": "forest_floor",
      "wall": "forest_wall",
      "monsters": [
        "rat",
        "wolf",
        "bee",
        "bear",
        "bat",
        "snake"
      ],
      "spawnMix": {
        "rat": [
          60,
          30,
          15,
          1,
          5
        ],
        "wolf": [
          1,
          25,
          20,
          20,
          0
        ],
        "bee": [
          null,
          4,
          20,
          24,
          0
        ],
        "bear": [
          null,
          null,
          15,
          25
        ],
        "bat": [
          40,
          25,
          15,
          5
        ],
        "snake": [
          null,
          20,
          20,
          10,
          0
        ]
      },
      "boss": "piper",
      "spawnInitial": [
        3,
        5,
        5,
        5
      ],
      "exitSprite": "exit_forest",
      "door": "bush",
      "spawnEvery": 25,
      "spawnCap": 100,
      "terrain": {
        "water": {
          "pools": [
            1,
            2
          ],
          "size": [
            4,
            10
          ]
        },
        "grass": {
          "patches": [
            2,
            4
          ],
          "size": [
            3,
            6
          ]
        }
      }
    },
    {
      "key": "cave",
      "name": "Caves",
      "floor": "floor",
      "wall": "wall",
      "monsters": [
        "spider",
        "harpy",
        "bear",
        "Goblin",
        "Goblin_archer"
      ],
      "boss": "golem",
      "door": "door",
      "terrain": {
        "rubble": {
          "patches": [
            2,
            4
          ],
          "size": [
            3,
            7
          ]
        }
      }
    },
    {
      "key": "crypt",
      "name": "Mummy's Crypt",
      "floor": "tomb_floor",
      "wall": "tomb_wall",
      "monsters": [
        "ghoul",
        "wraith",
        "phantom",
        "imp"
      ],
      "boss": "mummy",
      "door": "door"
    },
    {
      "key": "town",
      "name": "Town",
      "floor": "arcane_floor",
      "wall": "arcane_wall",
      "monsters": [
        "jackal",
        "hornet",
        "imp"
      ],
      "boss": "cultist",
      "bossCount": 3,
      "door": "door"
    },
    {
      "key": "lake",
      "name": "Haunted Lake",
      "floor": "space_floor",
      "wall": "space_wall",
      "monsters": [
        "keener",
        "imp",
        "emberfiend"
      ],
      "boss": "demigod",
      "final": true,
      "door": "door",
      "terrain": {
        "water": {
          "pools": [
            1,
            3
          ],
          "size": [
            5,
            14
          ]
        }
      }
    }
  ],
  "stats": {
    "STR": {
      "name": "Strength",
      "main": "Damage",
      "aux": "Weapon access (equip requirements)"
    },
    "INT": {
      "name": "Intelligence",
      "main": "Wand & spell power",
      "aux": "Identifying items"
    },
    "VIT": {
      "name": "Vitality",
      "main": "Health",
      "aux": "Damage resistance"
    },
    "DEX": {
      "name": "Dexterity",
      "main": "Accuracy",
      "aux": "Evasion"
    },
    "RES": {
      "name": "Resonance",
      "main": "Enchantment procs",
      "aux": "Magic resistance"
    },
    "LCK": {
      "name": "Luck",
      "main": "Critical hits",
      "aux": "A little of everything"
    }
  },
  "classes": {
    "warrior": {
      "name": "Chadwick",
      "icon": "⚔",
      "main": "STR",
      "secondary": "VIT",
      "unlock": "start",
      "stats": {
        "STR": 8,
        "INT": 3,
        "VIT": 7,
        "DEX": 4,
        "RES": 3,
        "LCK": 4
      },
      "start": {
        "weapon": "Shitty_sword",
        "armor": "Shitty_armor"
      },
      "baseHp": 18,
      "baseMp": 5,
      "regenTurns": 350,
      "vitRegen": 2,
      "mpRegenTurns": 600,
      "intRegen": 2,
      "levelUp": {
        "hp": 5,
        "mp": 2,
        "accuracy": 3,
        "evasion": 2,
        "crit": 1,
        "critDmg": 5
      },
      "blurb": "Front-line brawler. All around weapons master.",
      "skillTree": [
        {
          "id": "rush",
          "x": 0,
          "y": 0,
          "name": "Rush",
          "icon": "➤",
          "kind": "rush",
          "desc": "Move directly until collision. Deals damage to whatever you hit — the enemy, or yourself against a wall.",
          "levels": [
            "+0 damage, 100 turn cooldown",
            "+3 damage",
            "+5 damage, 50 turn cooldown",
            "can stun enemies 50% of the time"
          ],
          "ranks": [
            {
              "dmg": 0,
              "cd": 100
            },
            {
              "dmg": 3,
              "cd": 100
            },
            {
              "dmg": 5,
              "cd": 50
            },
            {
              "dmg": 5,
              "cd": 50,
              "stun": 0.5
            }
          ],
          "req": []
        },
        {
          "id": "spin",
          "x": 1,
          "y": 0,
          "name": "Spin",
          "icon": "↻",
          "kind": "spin",
          "desc": "Become a blender — strike every monster around you.",
          "levels": [
            "hit all adjacent foes, 80 turn cooldown",
            "+1 damage",
            "+1 damage, range 2 (hits within 2 tiles)",
            "free action — doesn't advance the turn clock"
          ],
          "ranks": [
            {
              "dmg": 0,
              "cd": 80,
              "range": 1
            },
            {
              "dmg": 1,
              "cd": 80,
              "range": 1
            },
            {
              "dmg": 1,
              "cd": 80,
              "range": 2
            },
            {
              "dmg": 1,
              "cd": 80,
              "range": 2,
              "freeAction": true
            }
          ],
          "req": []
        },
        {
          "id": "sword_master",
          "x": 2,
          "y": 0,
          "name": "Sword Master",
          "icon": "⚔",
          "kind": "passive",
          "when": "sword",
          "desc": "Mastery of the sword — passive bonuses that apply while a sword is equipped.",
          "levels": [
            "+1 damage for swords",
            "+2 damage for swords",
            "+4 damage for swords",
            "+6 damage and +15 accuracy for swords"
          ],
          "ranks": [
            {
              "dmg": 1
            },
            {
              "dmg": 2
            },
            {
              "dmg": 4
            },
            {
              "dmg": 6,
              "acc": 15
            }
          ],
          "req": []
        },
        {
          "id": "smite",
          "x": 0,
          "y": 1,
          "name": "Smite",
          "icon": "💥",
          "kind": "smite",
          "when": null,
          "desc": "A single devastating blow, empowered by your Strength. Tap a foe within range. Cooldown 100 turns, 5 MP.",
          "levels": [
            "Weapon damage + STR damage.",
            "Weapon damage + STR×1.5 damage.",
            "Weapon damage + STR×2 damage.",
            "Weapon damage + STR×2 damage, +1 range."
          ],
          "ranks": [
            {
              "strMult": 1
            },
            {
              "strMult": 1.5
            },
            {
              "strMult": 2
            },
            {
              "strMult": 2,
              "range": 2
            }
          ],
          "req": [],
          "reqAny": [
            [
              "rush",
              4
            ],
            [
              "spin",
              4
            ],
            [
              "sword_master",
              4
            ]
          ]
        },
        {
          "id": "raging_smite",
          "x": 0,
          "y": 2,
          "name": "Raging Smite",
          "icon": "🔥",
          "desc": "A Smite that drives the target into a berserk rage. 100 turn cooldown, 5 MP.",
          "levels": [
            "Deals Smite damage plus half your character level, and sends the target berserk.",
            "Cooldown 90.",
            "Also grants temporary STR and VIT equal to your character level, decaying by 1 every (character level) turns until the bonus is spent.",
            "A kill during the rage delays that decay by (character level) turns."
          ],
          "req": [
            [
              "smite",
              1
            ]
          ]
        },
        {
          "id": "healing_smite",
          "x": 1,
          "y": 2,
          "name": "Healing Smite",
          "icon": "✚",
          "desc": "A Smite that returns what it deals. 100 turn cooldown, 5 MP.",
          "levels": [
            "Deals Smite damage and heals you for the same amount.",
            "Cooldown 90.",
            "Cooldown 80.",
            "Cooldown 70, and healing beyond your maximum becomes a shield."
          ],
          "req": [
            [
              "smite",
              1
            ]
          ]
        },
        {
          "id": "spinning_smite",
          "x": 2,
          "y": 2,
          "name": "Spinning Smite",
          "icon": "🌀",
          "desc": "Spin and Smite as one blow. 100 turn cooldown, 5 MP.",
          "levels": [
            "Strikes everything within 2 tiles for Smite damage.",
            "Reaches 3 tiles.",
            "Reaches 3 tiles, cooldown 90.",
            "Reaches 4 tiles, cooldown 90, and every kill takes a further 10 turns off the cooldown."
          ],
          "req": [
            [
              "smite",
              "max"
            ],
            [
              "spin",
              "max"
            ]
          ]
        },
        {
          "id": "ketharas_will",
          "x": 0,
          "y": 3,
          "name": "Kethara's Will",
          "icon": "🛡",
          "kind": "passive",
          "desc": "An aura of Kethara's protection, covering you and anything fighting alongside you.",
          "levels": [
            "Allies and summons within 1 tile take 5% less damage.",
            "Within 2 tiles, 10% less.",
            "Within 3 tiles, 15% less.",
            "Within 4 tiles, 20% less."
          ],
          "req": [],
          "reqPoints": 12
        },
        {
          "id": "lay_on_hands",
          "x": 1,
          "y": 3,
          "name": "Lay on Hands",
          "icon": "🙌",
          "desc": "Mend yourself. Overhealing is not wasted — it shortens the wait. 200 turn cooldown, 15 MP.",
          "levels": [
            "Heals you for your VIT. Every point of healing beyond your maximum cuts 1 turn off the cooldown.",
            "Heals for VIT + STR.",
            "Heals for VIT + STR + your character level.",
            "Heals for (VIT + STR) + twice your character level."
          ],
          "req": [],
          "minLevel": 15
        }
      ]
    },
    "monk": {
      "name": "Brynn",
      "icon": "👊",
      "main": "DEX",
      "secondary": "VIT",
      "unlock": "start",
      "stats": {
        "STR": 4,
        "INT": 3,
        "VIT": 7,
        "DEX": 8,
        "RES": 3,
        "LCK": 4
      },
      "start": {
        "armor": "leather"
      },
      "baseHp": 16,
      "baseMp": 6,
      "regenTurns": 350,
      "vitRegen": 2,
      "mpRegenTurns": 600,
      "intRegen": 2,
      "levelUp": {
        "hp": 5,
        "mp": 2,
        "accuracy": 2,
        "evasion": 3,
        "crit": 1,
        "critDmg": 5
      },
      "blurb": "Fights best barehanded — hurls foes aside and lands harder the longer she goes unarmed.",
      "skillTree": [
        {
          "id": "throw",
          "x": 0,
          "y": 0,
          "name": "Throw",
          "icon": "↩",
          "kind": "throwmon",
          "when": null,
          "desc": "Grab an adjacent foe and hurl it away from you in a straight line until it collides with something. Cooldown 100 turns.",
          "levels": [
            "Throws the target backward until it collides with a wall or another monster. No damage.",
            "Same, and the thrown target takes weapon + DEX damage.",
            "Same, and also damages whatever else it collides with.",
            "Same, and reduces this skill's cooldown by however much total damage it dealt."
          ],
          "ranks": [
            {
              "dealDmg": false
            },
            {
              "dealDmg": true
            },
            {
              "dealDmg": true,
              "chain": true
            },
            {
              "dealDmg": true,
              "chain": true,
              "cdRefund": true
            }
          ],
          "req": []
        },
        {
          "id": "unarmed_master",
          "x": 1,
          "y": 0,
          "name": "Unarmed Master",
          "icon": "👊",
          "kind": "passive",
          "when": "unarmed",
          "desc": "Mastery of empty-handed combat — bonuses apply only while no weapon is equipped.",
          "levels": [
            "+1 min / +2 max unarmed damage. Unarmed attack speed 1.5.",
            "+2 min / +4 max unarmed damage. (requires character level 3)",
            "+4 min / +12 max unarmed damage. (requires character level 6)",
            "Same, plus (DEX+VIT)/2 bonus damage. (requires character level 9)"
          ],
          "ranks": [
            {
              "dmgMin": 1,
              "dmgMax": 2,
              "speed": 1.5
            },
            {
              "dmgMin": 2,
              "dmgMax": 4,
              "speed": 1.5,
              "minLevel": 3
            },
            {
              "dmgMin": 4,
              "dmgMax": 12,
              "speed": 1.5,
              "minLevel": 6
            },
            {
              "dmgMin": 4,
              "dmgMax": 12,
              "speed": 1.5,
              "minLevel": 9,
              "statScale": true
            }
          ],
          "req": []
        }
      ]
    },
    "adept": {
      "name": "Adept",
      "main": "INT",
      "secondary": "RES",
      "unlock": "town",
      "start": {
        "weapon": "dagger",
        "armor": null
      },
      "blurb": "Wands and enchantments over steel. (needs spells system)",
      "stats": {
        "STR": 5,
        "INT": 5,
        "VIT": 5,
        "DEX": 5,
        "RES": 5,
        "LCK": 5
      },
      "levelUp": {},
      "skillTree": []
    }
  },
  "gods": {
    "kethara": {
      "name": "Kethara",
      "domain": "Order & Domination",
      "unlock": "start",
      "boons": []
    },
    "maelon": {
      "name": "Maelon",
      "domain": "Death & Decomposition",
      "unlock": "town",
      "boons": []
    },
    "ourn": {
      "name": "Ourn",
      "domain": "Time",
      "unlock": "town",
      "boons": []
    },
    "label": {
      "name": "The Label",
      "domain": "Conjuration & Tempo",
      "unlock": "town",
      "boons": []
    },
    "guild": {
      "name": "The Guild",
      "domain": "Itemization & Customization",
      "unlock": "town",
      "boons": []
    },
    "auvris": {
      "name": "Auvris",
      "domain": "Nature & Inspiration",
      "unlock": "sealed",
      "boons": [],
      "note": "Sealed — unlocks after beating the game once."
    }
  }
};
