/* Cantori content data — generated by editor.html. Edit via the editor,
   or by hand (it's plain data). The game loads window.CANTORI_DATA. */
window.CANTORI_DATA = {
  "monsters": {
    "rat": {
      "name": "Rat",
      "hp": 10,
      "atkMin": 2,
      "atkMax": 4,
      "minFloor": 1,
      "glyph": "r",
      "color": "#c9b48f",
      "speed": 1,
      "acc": 8,
      "eva": 8
    },
    "bat": {
      "name": "Bat",
      "atkMin": 2,
      "atkMax": 3,
      "minFloor": 1,
      "glyph": "b",
      "color": "#b491d6",
      "hp": 5,
      "speed": 1.5,
      "acc": 9,
      "eva": 20
    },
    "snake": {
      "name": "Snake",
      "hp": 8,
      "atkMin": 3,
      "atkMax": 5,
      "glyph": "s",
      "color": "#7ec98a",
      "minFloor": 2,
      "speed": 1,
      "acc": 10,
      "eva": 25
    },
    "spider": {
      "name": "Spider",
      "atkMin": 3,
      "atkMax": 6,
      "minFloor": 3,
      "glyph": "x",
      "color": "#d68f8f",
      "speed": 1,
      "acc": 8,
      "eva": 6,
      "range": 4,
      "ranged": true,
      "hp": 20
    },
    "wolf": {
      "name": "Wolf",
      "atkMin": 4,
      "acc": 10,
      "glyph": "W",
      "color": "#9aa0a8",
      "hp": 28,
      "atkMax": 8,
      "speed": 1,
      "eva": 12,
      "minFloor": 2
    },
    "bee": {
      "name": "Bee",
      "hp": 15,
      "atkMin": 2,
      "atkMax": 6,
      "acc": 11,
      "eva": 16,
      "glyph": "e",
      "color": "#e6c34a",
      "minFloor": 3,
      "ranged": true,
      "range": 2,
      "speed": 1
    },
    "bear": {
      "name": "Bear",
      "hp": 12,
      "atkMin": 3,
      "atkMax": 5,
      "acc": 14,
      "eva": 1,
      "charge": true,
      "minFloor": 3,
      "glyph": "B",
      "color": "#8a6a44"
    },
    "harpy": {
      "name": "Harpy",
      "atkMin": 4,
      "atkMax": 12,
      "acc": 12,
      "eva": 14,
      "ranged": true,
      "range": 4,
      "glyph": "H",
      "color": "#6b6f7a",
      "minFloor": 4,
      "hp": 35
    },
    "jackal": {
      "name": "Jackal",
      "hp": 3,
      "atkMin": 1,
      "atkMax": 2,
      "glyph": "j",
      "color": "#b79a6b"
    },
    "hornet": {
      "name": "Hornet",
      "hp": 2,
      "atkMin": 2,
      "atkMax": 3,
      "glyph": "h",
      "color": "#e0a13c"
    },
    "ghoul": {
      "name": "Ghoul",
      "hp": 7,
      "atkMin": 3,
      "atkMax": 5,
      "minFloor": 1,
      "glyph": "G",
      "color": "#9fb07a"
    },
    "wraith": {
      "name": "Wraith",
      "hp": 6,
      "atkMin": 3,
      "atkMax": 4,
      "minFloor": 1,
      "glyph": "W",
      "color": "#8fa0c0"
    },
    "phantom": {
      "name": "Phantom",
      "hp": 5,
      "atkMin": 2,
      "atkMax": 4,
      "minFloor": 1,
      "glyph": "P",
      "color": "#7ee0d0"
    },
    "imp": {
      "name": "Imp",
      "hp": 5,
      "atkMin": 3,
      "atkMax": 5,
      "minFloor": 1,
      "glyph": "i",
      "color": "#c0c0e0"
    },
    "ufetubus": {
      "name": "Ufetubus",
      "hp": 4,
      "atkMin": 2,
      "atkMax": 4,
      "minFloor": 1,
      "glyph": "u",
      "color": "#6fb0d0"
    },
    "orange_demon": {
      "name": "Orange Demon",
      "hp": 10,
      "atkMin": 4,
      "atkMax": 7,
      "minFloor": 1,
      "glyph": "d",
      "color": "#e07030"
    }
  },
  "gear": {
    "dagger": {
      "cat": "weapon",
      "sub": "dagger",
      "name": "Dagger",
      "dmgMin": 1,
      "dmgMax": 3,
      "speed": 1.5,
      "tier": 1,
      "req": {
        "STR": 0
      },
      "glyph": "/",
      "color": "#cfc3a0",
      "accuracy": 10
    },
    "sword": {
      "cat": "weapon",
      "sub": "sword",
      "name": "Sword",
      "dmgMin": 3,
      "dmgMax": 6,
      "speed": 1,
      "glyph": "/",
      "color": "#d8e0ec",
      "tier": 1,
      "req": {
        "STR": 10
      },
      "accuracy": 5,
      "rarity": 15
    },
    "mace": {
      "cat": "weapon",
      "sub": "axe",
      "name": "Big axe",
      "dmgMin": 6,
      "dmgMax": 15,
      "speed": 0.9,
      "glyph": "/",
      "color": "#c8a878",
      "tier": 2,
      "req": {
        "STR": 15
      },
      "accuracy": -15,
      "rarity": 4
    },
    "leather": {
      "cat": "armor",
      "sub": "light",
      "name": "Leather Armor",
      "tier": 1,
      "req": {
        "STR": 0
      },
      "glyph": "[",
      "color": "#b98a5a",
      "defMin": 1,
      "defMax": 3
    },
    "chain": {
      "cat": "armor",
      "sub": "medium",
      "name": "Chain Mail",
      "tier": 2,
      "glyph": "[",
      "color": "#b9c0c8",
      "req": {
        "STR": 15
      },
      "defMin": 3,
      "defMax": 5
    },
    "plate": {
      "cat": "armor",
      "sub": "heavy",
      "name": "Plate Armor",
      "tier": 3,
      "glyph": "[",
      "color": "#dfe6f0",
      "req": {
        "STR": 40
      },
      "defMin": 6,
      "defMax": 10
    },
    "ring_copper": {
      "cat": "ring",
      "name": "Copper Ring",
      "tier": 1,
      "glyph": "o",
      "color": "#c58a4a"
    },
    "ring_silver": {
      "cat": "ring",
      "name": "Silver Ring",
      "tier": 2,
      "glyph": "o",
      "color": "#cfd4dc"
    },
    "charm_bone": {
      "cat": "trinket",
      "name": "Bone Charm",
      "tier": 1,
      "glyph": "*",
      "color": "#d8cfb0"
    },
    "amulet_jade": {
      "cat": "necklace",
      "name": "Jade Amulet",
      "tier": 2,
      "glyph": "\"",
      "color": "#7ec9a0"
    },
    "Axe": {
      "cat": "weapon",
      "sub": "axe",
      "name": "Axe",
      "dmgMax": 12,
      "tier": 1,
      "req": {
        "STR": 10
      },
      "glyph": "/",
      "color": "#cccccc",
      "dmgMin": 4,
      "speed": 0.9,
      "accuracy": -15,
      "rarity": 15
    },
    "spear": {
      "cat": "weapon",
      "sub": "spear",
      "name": "Spear",
      "dmgMin": 2,
      "dmgMax": 6,
      "speed": 0.9,
      "tier": 1,
      "req": {
        "STR": 8
      },
      "range": 2,
      "glyph": "/",
      "color": "#c8b890",
      "accuracy": 3,
      "rarity": 15
    },
    "bow": {
      "cat": "weapon",
      "sub": "bow",
      "name": "Short Bow",
      "dmgMin": 2,
      "dmgMax": 5,
      "speed": 1,
      "tier": 1,
      "req": {
        "STR": 5
      },
      "range": 5,
      "glyph": "}",
      "color": "#b08a4a",
      "accuracy": 5,
      "rarity": 15
    },
    "Shitty_dagger": {
      "cat": "weapon",
      "name": "Shitty Dagger",
      "dmgMin": 1,
      "dmgMax": 2,
      "accuracy": 5,
      "tier": 0,
      "req": {
        "STR": 0
      },
      "glyph": "/",
      "color": "#cccccc",
      "sub": "dagger",
      "speed": 1.2,
      "rarity": 0
    },
    "Shitty_armor": {
      "cat": "armor",
      "name": "Shitty armor",
      "req": {
        "STR": 0
      },
      "glyph": "/",
      "color": "#cccccc",
      "sub": "light",
      "defMin": 0,
      "defMax": 1,
      "tier": 0,
      "rarity": 0
    }
  },
  "loot": {
    "rarities": [
      {
        "key": "white",
        "name": "",
        "chance": 0.6,
        "color": "#e6e0d2"
      },
      {
        "key": "green",
        "name": "",
        "chance": 0.28,
        "color": "#7ec98a"
      },
      {
        "key": "blue",
        "name": "",
        "chance": 0.1,
        "color": "#5a9fe0"
      },
      {
        "key": "purple",
        "name": "",
        "chance": 0.02,
        "color": "#b491d6"
      },
      {
        "key": "gold",
        "name": "",
        "chance": 0,
        "color": "#f0c14b"
      }
    ],
    "statPool": [
      "STR",
      "INT",
      "VIT",
      "DEX",
      "RES",
      "LCK"
    ],
    "purpleSecondStatChance": 0.75,
    "categoryWeights": {
      "weapon": 40,
      "armor": 30,
      "ring": 12,
      "trinket": 9,
      "necklace": 9
    },
    "tierBands": [
      {
        "upToFloor": 5,
        "weights": [
          100,
          0,
          0
        ]
      },
      {
        "upToFloor": 10,
        "weights": [
          70,
          30,
          0
        ]
      },
      {
        "upToFloor": 15,
        "weights": [
          30,
          55,
          15
        ]
      },
      {
        "upToFloor": 20,
        "weights": [
          10,
          45,
          45
        ]
      },
      {
        "upToFloor": 25,
        "weights": [
          0,
          25,
          75
        ]
      }
    ],
    "enchants": {
      "fire": {
        "name": "Flaming",
        "icon": "🔥",
        "color": "#ff8f4a",
        "proc": 0.35,
        "slots": [
          "weapon",
          "armor",
          "ring",
          "trinket",
          "necklace"
        ],
        "desc": "Sears on a hit for half the source's power, then keeps burning for a few turns. Only one flame burns at a time.",
        "effect": {
          "type": "burn",
          "burstMult": 0.5,
          "dotTurns": 3
        }
      },
      "electric": {
        "name": "Charged",
        "icon": "⚡",
        "color": "#9ad0ff",
        "proc": 0.3,
        "slots": [
          "weapon",
          "armor",
          "ring",
          "trinket",
          "necklace"
        ],
        "desc": "A jolt equal to the source's power, with a chance to stun that fades against higher-level foes.",
        "effect": {
          "type": "shock",
          "burstMult": 1,
          "stunPer": 0.1
        }
      },
      "Speed": {
        "name": "Speed",
        "icon": "✦",
        "color": "#bfe0ff",
        "proc": 1,
        "slots": [
          "ring",
          "armor"
        ],
        "desc": "While worn, your attacks cost less time — you act faster.",
        "effect": {
          "type": "haste",
          "mult": 0.25
        }
      },
      "Thorns": {
        "name": "Thorns",
        "icon": "🜲",
        "color": "#cdd6a0",
        "proc": 0.5,
        "slots": [
          "armor",
          "necklace"
        ],
        "desc": "When you're struck, lash back at the attacker for half the damage you took.",
        "effect": {
          "type": "thorns",
          "mult": 0.5
        }
      },
      "Poison": {
        "name": "Poison",
        "icon": "☠",
        "color": "#9ad06a",
        "proc": 0.2,
        "slots": [
          "weapon"
        ],
        "desc": "A small bite now (+2), then 1 damage per turn for several turns. Every proc stacks another dose.",
        "effect": {
          "type": "poison",
          "initial": 2,
          "perTurn": 1,
          "turns": 5
        }
      }
    }
  },
  "consumables": {
    "heal": {
      "cat": "potion",
      "name": "Potion of Healing",
      "effect": "heal",
      "weight": 5,
      "glyph": "!",
      "color": "#e0685a"
    },
    "strength": {
      "cat": "potion",
      "name": "Potion of Strength",
      "effect": "strength",
      "weight": 2,
      "glyph": "!",
      "color": "#f0a838"
    },
    "poison": {
      "cat": "potion",
      "name": "Potion of Poison",
      "effect": "poison",
      "weight": 2,
      "glyph": "!",
      "color": "#7ec98a"
    },
    "mapping": {
      "cat": "scroll",
      "name": "Scroll of Magic Mapping",
      "effect": "map",
      "weight": 3,
      "glyph": "?",
      "color": "#cfe6b0"
    },
    "teleport": {
      "cat": "scroll",
      "name": "Scroll of Teleport",
      "effect": "teleport",
      "weight": 2,
      "glyph": "?",
      "color": "#b491d6"
    },
    "torch": {
      "cat": "tool",
      "name": "Torch",
      "effect": "burn",
      "noDrop": true,
      "glyph": "|",
      "color": "#f6b845"
    },
    "Vitality": {
      "cat": "potion",
      "name": "Potion of Vitality",
      "effect": "Vitality",
      "glyph": "!",
      "color": "#cccccc"
    }
  },
  "traps": {
    "teleport": {
      "name": "Teleport Trap",
      "effect": "teleport_far",
      "weight": 1,
      "glyph": "^",
      "color": "#b491d6"
    }
  },
  "bosses": {
    "piper": {
      "name": "The Pied Piper",
      "atkMin": 6,
      "atkMax": 10,
      "hp": 200
    },
    "golem": {
      "name": "Stone Golem",
      "hp": 55,
      "atkMin": 5,
      "atkMax": 8
    },
    "cultist": {
      "name": "Cultist",
      "hp": 20,
      "atkMin": 4,
      "atkMax": 6
    },
    "mummy": {
      "name": "The Mummy",
      "hp": 90,
      "atkMin": 7,
      "atkMax": 10
    },
    "demigod": {
      "name": "The Demi-God",
      "hp": 150,
      "atkMin": 9,
      "atkMax": 13
    }
  },
  "biomes": [
    {
      "key": "forest",
      "name": "Forest",
      "floor": "forest_floor",
      "wall": "forest_wall",
      "monsters": [
        "rat",
        "wolf",
        "bee",
        "bear",
        "harpy",
        "bat",
        "snake",
        "spider"
      ],
      "spawnMix": {
        "rat": [
          4,
          4,
          1,
          1,
          1
        ],
        "wolf": [
          1,
          2,
          3,
          4,
          4
        ],
        "spider": [
          3,
          3,
          3,
          2,
          2
        ],
        "bee": [
          null,
          4,
          3,
          4,
          3
        ],
        "bear": [
          null,
          null,
          3,
          3
        ],
        "harpy": [
          null,
          null,
          3,
          3
        ],
        "bat": [
          4,
          3,
          2,
          1
        ],
        "snake": [
          null,
          2,
          3,
          3,
          1
        ]
      },
      "boss": "piper",
      "spawnInitial": [
        3,
        5,
        5,
        5
      ],
      "spawnEvery": 14,
      "spawnCap": 16,
      "exitStyle": "wall",
      "exitSprite": "exit_forest",
      "door": "bush"
    },
    {
      "key": "cave",
      "name": "Cave",
      "floor": "floor",
      "wall": "wall",
      "monsters": [
        "rat",
        "bat",
        "snake",
        "spider"
      ],
      "boss": "golem",
      "door": "door"
    },
    {
      "key": "tomb",
      "name": "Tomb",
      "floor": "tomb_floor",
      "wall": "tomb_wall",
      "monsters": [
        "ghoul",
        "wraith",
        "phantom"
      ],
      "boss": "cultist",
      "bossCount": 3,
      "door": "door"
    },
    {
      "key": "arcane",
      "name": "Arcane Tomb",
      "floor": "arcane_floor",
      "wall": "arcane_wall",
      "monsters": [
        "wraith",
        "phantom",
        "imp"
      ],
      "boss": "mummy",
      "door": "door"
    },
    {
      "key": "space",
      "name": "The Beyond",
      "floor": "space_floor",
      "wall": "space_wall",
      "monsters": [
        "ufetubus",
        "imp",
        "orange_demon"
      ],
      "boss": "demigod",
      "final": true,
      "door": "door"
    }
  ],
  "stats": {
    "STR": {
      "name": "Strength",
      "main": "Damage",
      "aux": "Weapon access (equip requirements)"
    },
    "INT": {
      "name": "Intelligence",
      "main": "Wand & spell power",
      "aux": "Identifying items"
    },
    "VIT": {
      "name": "Vitality",
      "main": "Health",
      "aux": "Damage resistance"
    },
    "DEX": {
      "name": "Dexterity",
      "main": "Accuracy",
      "aux": "Evasion"
    },
    "RES": {
      "name": "Resonance",
      "main": "Enchantment procs",
      "aux": "Magic resistance"
    },
    "LCK": {
      "name": "Luck",
      "main": "Critical hits",
      "aux": "A little of everything"
    }
  },
  "classes": {
    "warrior": {
      "name": "Warrior",
      "main": "STR",
      "secondary": "VIT",
      "unlock": "start",
      "stats": {
        "STR": 8,
        "INT": 3,
        "VIT": 7,
        "DEX": 4,
        "RES": 3,
        "LCK": 4
      },
      "start": {
        "weapon": "Shitty_dagger",
        "armor": "Shitty_armor"
      },
      "baseHp": 18,
      "baseMp": 5,
      "regenTurns": 300,
      "vitRegen": 2,
      "mpRegenTurns": 600,
      "intRegen": 2,
      "levelUp": {
        "hp": 5,
        "mp": 2,
        "accuracy": 2,
        "evasion": 2,
        "crit": 1,
        "critDmg": 5
      },
      "blurb": "Front-line brawler. All around weapons master.",
      "skillTree": [
        [
          {
            "name": "Rush",
            "key": "rush",
            "icon": "➤",
            "kind": "rush",
            "desc": "Move directly until collision. Deals damage to whatever you hit — the enemy, or yourself against a wall.",
            "levels": [
              "+0 damage, 100 turn cooldown",
              "+3 damage",
              "+5 damage, 50 turn cooldown",
              "can stun enemies 50% of the time"
            ],
            "ranks": [
              {
                "dmg": 0,
                "cd": 100
              },
              {
                "dmg": 3,
                "cd": 100
              },
              {
                "dmg": 5,
                "cd": 50
              },
              {
                "dmg": 5,
                "cd": 50,
                "stun": 0.5
              }
            ],
            "req": []
          },
          {
            "name": "Spin",
            "key": "spin",
            "icon": "↻",
            "kind": "spin",
            "desc": "Become a blender — strike every monster around you.",
            "levels": [
              "hit all adjacent foes, 80 turn cooldown",
              "+1 damage",
              "+1 damage, range 2 (hits within 2 tiles)",
              "free action — doesn't advance the turn clock"
            ],
            "ranks": [
              {
                "dmg": 0,
                "cd": 80,
                "range": 1
              },
              {
                "dmg": 1,
                "cd": 80,
                "range": 1
              },
              {
                "dmg": 1,
                "cd": 80,
                "range": 2
              },
              {
                "dmg": 1,
                "cd": 80,
                "range": 2,
                "freeAction": true
              }
            ],
            "req": []
          },
          {
            "name": "Axe Master",
            "key": "axe_master",
            "icon": "🪓",
            "kind": "passive",
            "when": "axe",
            "desc": "Mastery of the axe — passive bonuses that apply while an axe is equipped.",
            "levels": [
              "+1 damage for axes",
              "+2 damage for axes",
              "+4 damage for axes",
              "+6 damage and +15 accuracy for axes"
            ],
            "ranks": [
              {
                "dmg": 1
              },
              {
                "dmg": 2
              },
              {
                "dmg": 4
              },
              {
                "dmg": 6,
                "acc": 15
              }
            ],
            "req": []
          },
          null,
          null
        ],
        [
          null,
          null,
          null,
          null,
          null
        ],
        [
          null,
          null,
          null,
          null,
          null
        ],
        [
          null,
          null,
          null,
          null,
          null
        ],
        [
          null,
          null,
          null,
          null,
          null
        ]
      ]
    },
    "duelist": {
      "name": "Duelist",
      "main": "DEX",
      "secondary": "LCK",
      "unlock": "start",
      "start": {
        "weapon": "dagger",
        "armor": "leather"
      },
      "blurb": "Fast and precise — evasion and critical strikes.",
      "stats": {
        "STR": 5,
        "INT": 5,
        "VIT": 5,
        "DEX": 5,
        "RES": 5,
        "LCK": 5
      },
      "levelUp": {},
      "skillTree": [
        [
          null,
          null,
          null,
          null,
          null
        ],
        [
          null,
          null,
          null,
          null,
          null
        ],
        [
          null,
          null,
          null,
          null,
          null
        ],
        [
          null,
          null,
          null,
          null,
          null
        ],
        [
          null,
          null,
          null,
          null,
          null
        ]
      ]
    },
    "adept": {
      "name": "Adept",
      "main": "INT",
      "secondary": "RES",
      "unlock": "town",
      "start": {
        "weapon": "dagger",
        "armor": null
      },
      "blurb": "Wands and enchantments over steel. (needs spells system)",
      "stats": {
        "STR": 5,
        "INT": 5,
        "VIT": 5,
        "DEX": 5,
        "RES": 5,
        "LCK": 5
      },
      "levelUp": {},
      "skillTree": [
        [
          null,
          null,
          null,
          null,
          null
        ],
        [
          null,
          null,
          null,
          null,
          null
        ],
        [
          null,
          null,
          null,
          null,
          null
        ],
        [
          null,
          null,
          null,
          null,
          null
        ],
        [
          null,
          null,
          null,
          null,
          null
        ]
      ]
    },
    "warden": {
      "name": "Warden",
      "main": "VIT",
      "secondary": "STR",
      "unlock": "town",
      "start": {
        "weapon": "mace",
        "armor": "chain"
      },
      "blurb": "Immovable. Trades speed for raw durability.",
      "stats": {
        "STR": 5,
        "INT": 5,
        "VIT": 5,
        "DEX": 5,
        "RES": 5,
        "LCK": 5
      },
      "levelUp": {},
      "skillTree": [
        [
          null,
          null,
          null,
          null,
          null
        ],
        [
          null,
          null,
          null,
          null,
          null
        ],
        [
          null,
          null,
          null,
          null,
          null
        ],
        [
          null,
          null,
          null,
          null,
          null
        ],
        [
          null,
          null,
          null,
          null,
          null
        ]
      ]
    }
  },
  "gods": {
    "kethara": {
      "name": "Kethara",
      "domain": "Order & Domination",
      "unlock": "start",
      "boons": []
    },
    "maelon": {
      "name": "Maelon",
      "domain": "Death & Decomposition",
      "unlock": "town",
      "boons": []
    },
    "ourn": {
      "name": "Ourn",
      "domain": "Time",
      "unlock": "town",
      "boons": []
    },
    "label": {
      "name": "The Label",
      "domain": "Conjuration & Tempo",
      "unlock": "town",
      "boons": []
    },
    "guild": {
      "name": "The Guild",
      "domain": "Itemization & Customization",
      "unlock": "town",
      "boons": []
    },
    "auvris": {
      "name": "Auvris",
      "domain": "Nature & Inspiration",
      "unlock": "sealed",
      "boons": [],
      "note": "Sealed — unlocks after beating the game once."
    }
  }
};
