#!/usr/bin/env python3
"""Regenerate docs/MAP.md — the navigation index for game.js.

game.js is ~5,200 lines / ~77k tokens. Reading it whole costs real money on every
packet and buries the model in code it doesn't need. This emits a section index
(banner -> line range -> rough token cost) so a packet can Read just its section
with offset/limit.

Line numbers drift with every edit, so rerun this whenever game.js changes
structurally:

    python3 tools/make_map.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
DOCS = os.path.join(ROOT, "docs")

# Files a packet may need to read whole — small enough not to worry about.
SMALL = ["data.js", "loot.js", "index.html", "styles.css", "CLAUDE.md"]


def est_tokens(text):
    """Rough token estimate. Source code runs ~3.5 chars/token."""
    return int(len(text) / 3.5)


def sections(path):
    """Every `// ---- Name ----` banner in game.js, with its line span."""
    lines = open(path, encoding="utf-8").read().split("\n")
    found = []
    for i, l in enumerate(lines, 1):
        m = re.match(r"\s*// ---- (.+?) -*$", l)
        if m:
            found.append((i, m.group(1).strip()))
    out = []
    for j, (start, name) in enumerate(found):
        end = (found[j + 1][0] - 1) if j + 1 < len(found) else len(lines)
        body = "\n".join(lines[start - 1:end])
        out.append((start, end, name, est_tokens(body)))
    return out, len(lines)


def main():
    game = os.path.join(ROOT, "game.js")
    secs, total_lines = sections(game)
    whole = est_tokens(open(game, encoding="utf-8").read())

    L = []
    L.append("<!-- GENERATED by tools/make_map.py — do not edit by hand. -->")
    L.append("# Where things live in `game.js`")
    L.append("")
    L.append("`game.js` is **%d lines, ~%dk tokens**. Reading it whole is the single most "
             "expensive thing a packet can do, and it buries the useful code in noise."
             % (total_lines, whole // 1000))
    L.append("")
    L.append("**Read the section you need, not the file.** Every section below is a")
    L.append("`// ---- Name ----` banner in `game.js`:")
    L.append("")
    L.append("```")
    L.append("Read(game.js, offset=<start>, limit=<end - start + 1>)")
    L.append("```")
    L.append("")
    L.append("To find a symbol without reading anything, use Grep — `function name`,")
    L.append("`const name =`, or the call site.")
    L.append("")
    L.append("| Lines | ~tokens | Section |")
    L.append("|---:|---:|---|")
    for start, end, name, tok in secs:
        L.append("| %d–%d | %s | %s |" % (start, end, ("%.1fk" % (tok / 1000)) if tok >= 1000 else str(tok), name))
    L.append("")
    L.append("## Other files")
    L.append("")
    L.append("| File | ~tokens | Read whole? |")
    L.append("|---|---:|---|")
    for f in SMALL:
        p = os.path.join(ROOT, f)
        if not os.path.exists(p):
            continue
        t = est_tokens(open(p, encoding="utf-8").read())
        ok = "yes" if t < 12000 else "prefer Grep"
        L.append("| `%s` | %s | %s |" % (f, ("%.1fk" % (t / 1000)) if t >= 1000 else str(t), ok))
    ed = os.path.join(ROOT, "editor.js")
    if os.path.exists(ed):
        t = est_tokens(open(ed, encoding="utf-8").read())
        L.append("| `editor.js` | %.0fk | no — Grep for the table/tab you're changing |" % (t / 1000))
    L.append("")
    L.append("`data.js` is one big JSON literal — Grep for the key (`\"monsters\"`, ")
    L.append("`\"biomes\"`, `\"classes\"`) and read that range rather than the whole file.")
    L.append("")

    os.makedirs(DOCS, exist_ok=True)
    out = os.path.join(DOCS, "MAP.md")
    open(out, "w", encoding="utf-8").write("\n".join(L))
    print("wrote docs/MAP.md — %d sections, game.js is %d lines / ~%dk tokens"
          % (len(secs), total_lines, whole // 1000))


if __name__ == "__main__":
    main()
